# Use the official Node.js image
FROM node:18

WORKDIR /app

COPY frontend/ .
RUN npm install


Expose 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]


# production mode
# RUN npm run build -- --configuration production

# FROM nginx:alpine

# COPY --from=build /app/dist/frontend /usr/share/nginx/html

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]